// Shared page options for admin forms (meta-details, page-titles, etc.)
export interface PageOption {
    value: string;
    label: string;
}

export const pageOptions: PageOption[] = [
    { value: 'home', label: 'Home' },
    { value: 'about-company', label: 'About Company' },
    { value: 'features', label: 'Features' },
    { value: 'faq', label: 'FAQ' },
    { value: 'contact', label: 'Contact' },
    { value: 'free-mlm-software-demo', label: 'Demo' },
    { value: 'blog', label: 'Blog' },
    { value: 'press-release', label: 'Press Release' },
    { value: 'pricing', label: 'Pricing' },
    { value: 'auto-responder-module', label: 'Pricing: Auto Responder Module' },
    { value: 'cloud-mlm-software-basic', label: 'Pricing: Cloud MLM Software Basic' },
    { value: 'drupal-cms-website', label: 'Pricing: Drupal CMS Website' },
    { value: 'email', label: 'Pricing: Email' },
    { value: 'lcp-page-development', label: 'Pricing: LCP Page Development' },
    { value: 'magento-integration', label: 'Pricing: Magento Integration' },
    { value: 'multi-currency-system', label: 'Pricing: Multi-Currency System' },
    { value: 'multilingual-system', label: 'Pricing: Multilingual System' },
    { value: 'native-android-app-with-mlm-software', label: 'Pricing: Native Android App' },
    { value: 'opencart-integration', label: 'Pricing: OpenCart Integration' },
    { value: 'payment-gateway-integration', label: 'Pricing: Payment Gateway Integration' },
    { value: 'privileged-user-system-module', label: 'Pricing: Privileged User System Module' },
    { value: 'replicating-website-for-mlm-business', label: 'Pricing: Replicating Website for MLM Business' },
    { value: 'support-ticket-system-module-for-mlm-software', label: 'Pricing: Support Ticket System Module' },
    { value: 'wordpress-cms-website', label: 'Pricing: WordPress CMS Website' },
    { value: 'network-marketing-software', label: 'Network Marketing Software' },
    { value: 'direct-selling-software', label: 'Direct Selling Software' },
    { value: 'crm-mlm-software', label: 'CRM MLM Software' },
    { value: 'bitcoin-cryptocurrency-mlm-software', label: 'Bitcoin & Cryptocurrency MLM Software' },
    { value: 'testimonials', label: 'Testimonials' },
    { value: 'mlm-software-modules', label: 'Modules' },
    { value: 'mlm-software-integration', label: 'Integration' },
    { value: 'mlm-plans', label: 'MLM Plans' },
    { value: 'services', label: 'Services' },
    { value: 'industries', label: 'Industries' },
    { value: 'changelog', label: 'Changelog' },
    { value: 'ai-copilot', label: 'AI Co-pilot' },
];

// Page display names for tables
export const pageDisplayNames: Record<string, string> = {
    'home': 'Home',
    'about-company': 'About Company',
    'features': 'Features',
    'faq': 'FAQ',
    'contact': 'Contact',
    'free-mlm-software-demo': 'Demo',
    'blog': 'Blog',
    'press-release': 'Press Release',
    'pricing': 'Pricing',
    'auto-responder-module': 'Pricing: Auto Responder Module',
    'cloud-mlm-software-basic': 'Pricing: Cloud MLM Software Basic',
    'drupal-cms-website': 'Pricing: Drupal CMS Website',
    'email': 'Pricing: Email',
    'lcp-page-development': 'Pricing: LCP Page Development',
    'magento-integration': 'Pricing: Magento Integration',
    'multi-currency-system': 'Pricing: Multi-Currency System',
    'multilingual-system': 'Pricing: Multilingual System',
    'native-android-app-with-mlm-software': 'Pricing: Native Android App',
    'opencart-integration': 'Pricing: OpenCart Integration',
    'payment-gateway-integration': 'Pricing: Payment Gateway Integration',
    'privileged-user-system-module': 'Pricing: Privileged User System Module',
    'replicating-website-for-mlm-business': 'Pricing: Replicating Website for MLM Business',
    'support-ticket-system-module-for-mlm-software': 'Pricing: Support Ticket System Module',
    'wordpress-cms-website': 'Pricing: WordPress CMS Website',
    'network-marketing-software': 'Network Marketing Software',
    'direct-selling-software': 'Direct Selling Software',
    'crm-mlm-software': 'CRM MLM Software',
    'bitcoin-cryptocurrency-mlm-software': 'Bitcoin & Cryptocurrency MLM Software',
    'testimonials': 'Testimonials',
    'mlm-software-modules': 'Modules',
    'mlm-software-integration': 'Integration',
    'mlm-plans': 'MLM Plans',
    'services': 'Services',
    'industries': 'Industries',
    'changelog': 'Changelog',
    'ai-copilot': 'AI Co-pilot',
};
