ADDITIONAL_CONFIG = PosixPath('/app/data/settings-override.py')  ###
ADDON_ACTIVITY_LOG_EXPIRY = 180  ###
ADMINS = (('Weblate Admin', 'admin@example.com'),)
ADMINS_BILLING = []  ###
ADMINS_CONTACT = []  ###
ADMINS_HOSTING = []  ###
ALLOWED_ASSET_DOMAINS = ['*']  ###
ALLOWED_ASSET_SIZE = 4194304  ###
ALLOWED_HOSTS = ['*']
ALTCHA_MAX_NUMBER = 1000000  ###
ANONYMOUS_USER_NAME = 'anonymous'  ###
AUDITLOG_EXPIRY = 180  ###
AUTHENTICATION_BACKENDS = ('social_core.backends.email.EmailAuth', 'weblate.accounts.auth.WeblateUserBackend')
AUTH_LDAP_SERVER_URI = None  ###
AUTH_LOCK_ATTEMPTS = 10  ###
AUTH_PASSWORD_DAYS = 180  ###
AUTH_PASSWORD_VALIDATORS = [{'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'}, {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}}, {'NAME': 'weblate.accounts.password_validation.MaximalLengthValidator'}, {'NAME': 'weblate.accounts.password_validation.PastPasswordsValidator'}, {'NAME': 'django_zxcvbn_password_validator.ZxcvbnPasswordValidator'}]
AUTH_RESTRICT_ADMINS = {}  ###
AUTH_TOKEN_VALID = 172800  ###
AUTH_USER_MODEL = 'weblate_auth.User'
AUTOFIX_LIST = ['weblate.trans.autofixes.whitespace.SameBookendingWhitespace', 'weblate.trans.autofixes.chars.ReplaceTrailingDotsWithEllipsis', 'weblate.trans.autofixes.chars.RemoveZeroSpace', 'weblate.trans.autofixes.chars.RemoveControlChars', 'weblate.trans.autofixes.chars.DevanagariDanda', 'weblate.trans.autofixes.html.BleachHTML']  ###
AUTO_UPDATE = False  ###
AVATAR_DEFAULT_IMAGE = 'identicon'  ###
AVATAR_URL_PREFIX = 'https://www.gravatar.com/'  ###
AZURE_DEVOPS_CREDENTIALS = {}  ###
BACKGROUND_ADMIN_CHECKS = True  ###
BACKGROUND_TASKS = 'monthly'  ###
BASIC_LANGUAGES = None  ###
BITBUCKETCLOUD_CREDENTIALS = {}  ###
BITBUCKETSERVER_CREDENTIALS = {}  ###
BORG_EXTRA_ARGS = []  ###
CACHES = {'default': {'BACKEND': 'django_redis.cache.RedisCache', 'LOCATION': 'redis://cache:6379/1', 'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient', 'CONNECTION_POOL_KWARGS': {}}, 'KEY_PREFIX': 'weblate', 'TIMEOUT': 3600}, 'avatar': {'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache', 'LOCATION': '/app/cache/avatar', 'TIMEOUT': 86400, 'OPTIONS': {'MAX_ENTRIES': 1000}}}
CACHE_DIR = '/app/cache'  ###
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'  ###
CELERY_BROKER_CONNECTION_RETRY = True  ###
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  ###
CELERY_BROKER_URL = 'redis://cache:6379/1'  ###
CELERY_RESULT_BACKEND = 'redis://cache:6379/1'  ###
CELERY_TASK_ALWAYS_EAGER = False  ###
CELERY_TASK_ROUTES = {'weblate.trans.tasks.auto_translate*': {'queue': 'translate'}, 'weblate.accounts.tasks.notify_*': {'queue': 'notify'}, 'weblate.accounts.tasks.send_mails': {'queue': 'notify'}, 'weblate.addons.tasks.addon_change': {'queue': 'notify'}, 'weblate.utils.tasks.settings_backup': {'queue': 'backup'}, 'weblate.utils.tasks.database_backup': {'queue': 'backup'}, 'weblate.wladmin.tasks.backup': {'queue': 'backup'}, 'weblate.wladmin.tasks.backup_service': {'queue': 'backup'}, 'weblate.memory.tasks.*': {'queue': 'memory'}}  ###
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 250000  ###
CHECK_LIST = ['weblate.checks.same.SameCheck', 'weblate.checks.chars.BeginNewlineCheck', 'weblate.checks.chars.EndNewlineCheck', 'weblate.checks.chars.BeginSpaceCheck', 'weblate.checks.chars.EndSpaceCheck', 'weblate.checks.chars.DoubleSpaceCheck', 'weblate.checks.chars.EndStopCheck', 'weblate.checks.chars.EndColonCheck', 'weblate.checks.chars.EndQuestionCheck', 'weblate.checks.chars.EndExclamationCheck', 'weblate.checks.chars.EndInterrobangCheck', 'weblate.checks.chars.EndEllipsisCheck', 'weblate.checks.chars.EndSemicolonCheck', 'weblate.checks.chars.MaxLengthCheck', 'weblate.checks.chars.KashidaCheck', 'weblate.checks.chars.PunctuationSpacingCheck', 'weblate.checks.chars.KabyleCharactersCheck', 'weblate.checks.format.PythonFormatCheck', 'weblate.checks.format.PythonBraceFormatCheck', 'weblate.checks.format.PHPFormatCheck', 'weblate.checks.format.CFormatCheck', 'weblate.checks.format.PerlFormatCheck', 'weblate.checks.format.PerlBraceFormatCheck', 'weblate.checks.format.JavaScriptFormatCheck', 'weblate.checks.format.LuaFormatCheck', 'weblate.checks.format.ObjectPascalFormatCheck', 'weblate.checks.format.SchemeFormatCheck', 'weblate.checks.format.CSharpFormatCheck', 'weblate.checks.format.JavaFormatCheck', 'weblate.checks.format.JavaMessageFormatCheck', 'weblate.checks.format.PercentPlaceholdersCheck', 'weblate.checks.format.VueFormattingCheck', 'weblate.checks.format.I18NextInterpolationCheck', 'weblate.checks.format.ESTemplateLiteralsCheck', 'weblate.checks.format.AutomatticComponentsCheck', 'weblate.checks.angularjs.AngularJSInterpolationCheck', 'weblate.checks.icu.ICUMessageFormatCheck', 'weblate.checks.icu.ICUSourceCheck', 'weblate.checks.qt.QtFormatCheck', 'weblate.checks.qt.QtPluralCheck', 'weblate.checks.ruby.RubyFormatCheck', 'weblate.checks.consistency.PluralsCheck', 'weblate.checks.consistency.SamePluralsCheck', 'weblate.checks.consistency.ConsistencyCheck', 'weblate.checks.consistency.ReusedCheck', 'weblate.checks.consistency.TranslatedCheck', 'weblate.checks.chars.EscapedNewlineCountingCheck', 'weblate.checks.chars.NewLineCountCheck', 'weblate.checks.markup.BBCodeCheck', 'weblate.checks.chars.ZeroWidthSpaceCheck', 'weblate.checks.render.MaxSizeCheck', 'weblate.checks.markup.XMLValidityCheck', 'weblate.checks.markup.XMLTagsCheck', 'weblate.checks.markup.MarkdownRefLinkCheck', 'weblate.checks.markup.MarkdownLinkCheck', 'weblate.checks.markup.MarkdownSyntaxCheck', 'weblate.checks.markup.URLCheck', 'weblate.checks.markup.SafeHTMLCheck', 'weblate.checks.markup.RSTReferencesCheck', 'weblate.checks.markup.RSTSyntaxCheck', 'weblate.checks.placeholders.PlaceholderCheck', 'weblate.checks.placeholders.RegexCheck', 'weblate.checks.duplicate.DuplicateCheck', 'weblate.checks.source.OptionalPluralCheck', 'weblate.checks.source.EllipsisCheck', 'weblate.checks.source.MultipleFailingCheck', 'weblate.checks.source.LongUntranslatedCheck', 'weblate.checks.format.MultipleUnnamedFormatsCheck', 'weblate.checks.glossary.GlossaryCheck', 'weblate.checks.glossary.ProhibitedInitialCharacterCheck', 'weblate.checks.fluent.syntax.FluentSourceSyntaxCheck', 'weblate.checks.fluent.syntax.FluentTargetSyntaxCheck', 'weblate.checks.fluent.parts.FluentPartsCheck', 'weblate.checks.fluent.references.FluentReferencesCheck', 'weblate.checks.fluent.inner_html.FluentSourceInnerHTMLCheck', 'weblate.checks.fluent.inner_html.FluentTargetInnerHTMLCheck']  ###
COMMENT_CLEANUP_DAYS = None  ###
COMMIT_PENDING_HOURS = 24  ###
COMPRESSORS = {'css': 'compressor.css.CssCompressor', 'js': 'compressor.js.JsCompressor'}  ###
COMPRESS_CACHEABLE_PRECOMPILERS = ()  ###
COMPRESS_CACHE_BACKEND = 'default'  ###
COMPRESS_CACHE_KEY_FUNCTION = 'compressor.cache.simple_cachekey'  ###
COMPRESS_CLEAN_CSS_ARGUMENTS = ''  ###
COMPRESS_CLEAN_CSS_BINARY = 'cleancss'  ###
COMPRESS_CLOSURE_COMPILER_ARGUMENTS = ''  ###
COMPRESS_CLOSURE_COMPILER_BINARY = 'java -jar compiler.jar'  ###
COMPRESS_CSS_HASHING_METHOD = 'content'  ###
COMPRESS_DATA_URI_MAX_SIZE = 1024  ###
COMPRESS_DEBUG_TOGGLE = None  ###
COMPRESS_ENABLED = True  ###
COMPRESS_FILTERS = {'css': ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.rCSSMinFilter'], 'js': ['compressor.filters.jsmin.rJSMinFilter']}  ###
COMPRESS_JINJA2_GET_ENVIRONMENT = <function CompressorConf.JINJA2_GET_ENVIRONMENT at 0xffff76ce6820>  ###
COMPRESS_MINT_DELAY = 30  ###
COMPRESS_MTIME_DELAY = 10  ###
COMPRESS_OFFLINE = True  ###
COMPRESS_OFFLINE_CONTEXT = 'weblate.utils.compress.offline_context'  ###
COMPRESS_OFFLINE_MANIFEST = 'manifest.json'  ###
COMPRESS_OFFLINE_MANIFEST_STORAGE = 'compressor.storage.OfflineManifestFileStorage'  ###
COMPRESS_OFFLINE_MANIFEST_STORAGE_ALIAS = 'compressor-offine'  ###
COMPRESS_OFFLINE_TIMEOUT = 31536000  ###
COMPRESS_OUTPUT_DIR = 'CACHE'  ###
COMPRESS_PARSER = 'compressor.parser.AutoSelectParser'  ###
COMPRESS_PRECOMPILERS = ()  ###
COMPRESS_REBUILD_TIMEOUT = 2592000  ###
COMPRESS_ROOT = '/app/cache/static'  ###
COMPRESS_STORAGE = 'compressor.storage.CompressorFileStorage'  ###
COMPRESS_STORAGE_ALIAS = 'compressor'  ###
COMPRESS_TEMPLATE_FILTER_CONTEXT = {'STATIC_URL': '/static/'}  ###
COMPRESS_URL = '/static/'  ###
COMPRESS_URL_PLACEHOLDER = '/__compressor_url_placeholder__/'  ###
COMPRESS_VERBOSE = False  ###
COMPRESS_YUGLIFY_BINARY = 'yuglify'  ###
COMPRESS_YUGLIFY_CSS_ARGUMENTS = '--terminal'  ###
COMPRESS_YUGLIFY_JS_ARGUMENTS = '--terminal'  ###
COMPRESS_YUI_BINARY = 'java -jar yuicompressor.jar'  ###
COMPRESS_YUI_CSS_ARGUMENTS = ''  ###
COMPRESS_YUI_JS_ARGUMENTS = ''  ###
CONTACT_FORM = 'reply-to'  ###
CORS_ALLOWED_ORIGINS = []  ###
CORS_ALLOW_ALL_ORIGINS = False  ###
CORS_URLS_REGEX = '^/api/.*$'  ###
CREATE_GLOSSARIES = True  ###
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'  ###
CRISPY_TEMPLATE_PACK = 'bootstrap5'  ###
CSP_CONNECT_SRC = []  ###
CSP_FONT_SRC = []  ###
CSP_FORM_SRC = []  ###
CSP_IMG_SRC = []  ###
CSP_SCRIPT_SRC = []  ###
CSP_STYLE_SRC = []  ###
CSRF_COOKIE_HTTPONLY = True
CSRF_FAILURE_VIEW = 'weblate.trans.views.error.csrf_failure'
CSRF_USE_SESSIONS = True
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql', 'NAME': 'weblate', 'USER': 'weblate', 'ALTER_ROLE': 'weblate', 'PASSWORD': 'weblate', 'HOST': 'weblate-db', 'PORT': '', 'OPTIONS': {'sslmode': 'prefer'}, 'CONN_MAX_AGE': None, 'CONN_HEALTH_CHECKS': True, 'DISABLE_SERVER_SIDE_CURSORS': False, 'ATOMIC_REQUESTS': False, 'AUTOCOMMIT': True, 'TIME_ZONE': None, 'TEST': {'CHARSET': None, 'COLLATION': None, 'MIGRATE': True, 'MIRROR': None, 'NAME': None}}}
DATABASE_BACKUP = 'plain'  ###
DATA_DIR = '/app/data'  ###
DATA_UPLOAD_MAX_MEMORY_SIZE = 50000000
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000
DEFAULT_ACCESS_CONTROL = 0  ###
DEFAULT_ADDONS = {}  ###
DEFAULT_ADDON_MESSAGE = 'Update translation files\n\nUpdated by "{{ addon_name }}" add-on in Weblate.\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}'  ###
DEFAULT_ADD_MESSAGE = 'Added translation using Weblate ({{ language_name }})\n\n'  ###
DEFAULT_AUTOCLEAN_TM = False  ###
DEFAULT_AUTO_LOCK_ERROR = True  ###
DEFAULT_AUTO_WATCH = True  ###
DEFAULT_COMMITER_EMAIL = 'noreply@weblate.org'  ###
DEFAULT_COMMITER_NAME = 'Weblate'  ###
DEFAULT_COMMIT_MESSAGE = 'Translated using Weblate ({{ language_name }})\n\nCurrently translated at {{ stats.translated_percent }}% ({{ stats.translated }} of {{ stats.all }} strings)\n\nTranslation: {{ project_name }}/{{ component_name }}\nTranslate-URL: {{ url }}'  ###
DEFAULT_DELETE_MESSAGE = 'Deleted translation using Weblate ({{ language_name }})\n\n'  ###
DEFAULT_EXCEPTION_REPORTER_FILTER = 'weblate.trans.debug.WeblateExceptionReporterFilter'
DEFAULT_FROM_EMAIL = 'weblate@example.com'
DEFAULT_LANGUAGE = 'en'  ###
DEFAULT_LOG = ['console']  ###
DEFAULT_LOGLEVEL = 'INFO'  ###
DEFAULT_MERGE_MESSAGE = "Merge branch '{{ component_remote_branch }}' into Weblate.\n\n"  ###
DEFAULT_MERGE_STYLE = 'rebase'  ###
DEFAULT_PAGE_LIMIT = 100  ###
DEFAULT_PULL_MESSAGE = 'Translations update from {{ site_title }}\n\nTranslations update from [{{ site_title }}]({{ site_url }}) for [{{ project_name }}/{{ component_name }}]({{url}}).\n\n{% if component_linked_children %}\nIt also includes following components:\n{% for linked in component_linked_children %}\n* [{{ linked.project_name }}/{{ linked.name }}]({{ linked.url }})\n{% endfor %}\n{% endif %}\n\nCurrent translation status:\n\n![Weblate translation status]({{widget_url}})\n'  ###
DEFAULT_PUSH_ON_COMMIT = True  ###
DEFAULT_RESTRICTED_COMPONENT = False  ###
DEFAULT_SHARED_TM = True  ###
DEFAULT_TRANSLATION_PROPAGATION = True  ###
DEFAULT_VCS = 'git'  ###
DRF_STANDARDIZED_ERRORS = {'ALLOWED_ERROR_STATUS_CODES': ['400', '401', '403', '404', '405', '406', '415', '423', '429', '500'], 'ERROR_SCHEMAS': {'423': 'weblate.api.serializers.ErrorResponse423Serializer'}, 'EXCEPTION_HANDLER_CLASS': 'weblate.api.views.WeblateExceptionHandler'}  ###
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_PASSWORD = None
EMAIL_HOST_USER = None
EMAIL_SEND_HTML = True  ###
EMAIL_SUBJECT_PREFIX = '[Weblate] '
EMAIL_USE_TLS = True
ENABLE_AVATARS = True  ###
ENABLE_HOOKS = True  ###
ENABLE_HTTPS = False  ###
ENABLE_SHARING = False  ###
EXTRA_HTML_HEAD = ''  ###
FONTS_CDN_URL = None  ###
FORMS_URLFIELD_ASSUME_HTTPS = True
GET_HELP_URL = None  ###
GITEA_CREDENTIALS = {}  ###
GITHUB_CREDENTIALS = {}  ###
GITLAB_CREDENTIALS = {}  ###
GOOGLE_ANALYTICS_ID = None  ###
HAVE_SYSLOG = False  ###
HIDE_REPO_CREDENTIALS = True  ###
HIDE_VERSION = False  ###
INSTALLED_APPS = ['customize', 'weblate.addons', 'weblate.auth', 'weblate.checks', 'weblate.formats', 'weblate.glossary', 'weblate.machinery', 'weblate.trans', 'weblate.lang', 'weblate_language_data', 'weblate.memory', 'weblate.screenshots', 'weblate.fonts', 'weblate.accounts', 'weblate.configuration', 'weblate.utils', 'weblate.vcs', 'weblate.wladmin', 'weblate.metrics', 'weblate', 'weblate.gitexport', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.staticfiles', 'django.contrib.admin', 'django.contrib.sitemaps', 'django.contrib.humanize', 'social_django', 'crispy_forms', 'crispy_bootstrap5', 'compressor', 'rest_framework', 'rest_framework.authtoken', 'django_filters', 'django_celery_beat', 'corsheaders', 'django_otp', 'django_otp.plugins.otp_static', 'django_otp.plugins.otp_totp', 'django_otp_webauthn', 'drf_spectacular', 'drf_spectacular_sidecar', 'drf_standardized_errors', 'django_zxcvbn_password_validator']
INVOICE_PATH = ''  ###
INVOICE_PATH_LEGACY = ''  ###
IP_ADDRESSES = []  ###
IP_BEHIND_REVERSE_PROXY = False  ###
IP_PROXY_HEADER = None  ###
IP_PROXY_OFFSET = -1  ###
LANGUAGES = (('ar', 'العربية'), ('az', 'Azərbaycan'), ('ba', 'башҡорт теле'), ('be', 'Беларуская'), ('be-latn', 'Biełaruskaja'), ('bg', 'Български'), ('br', 'Brezhoneg'), ('ca', 'Català'), ('cs', 'Čeština'), ('cy', 'Cymraeg'), ('da', 'Dansk'), ('de', 'Deutsch'), ('en', 'English'), ('el', 'Ελληνικά'), ('en-gb', 'English (United Kingdom)'), ('es', 'Español'), ('fi', 'Suomi'), ('fr', 'Français'), ('ga', 'Gaeilge'), ('gl', 'Galego'), ('he', 'עברית'), ('hu', 'Magyar'), ('hr', 'Hrvatski'), ('id', 'Indonesia'), ('is', 'Íslenska'), ('it', 'Italiano'), ('ja', '日本語'), ('kab', 'Taqbaylit'), ('kk', 'Қазақ тілі'), ('ko', '한국어'), ('nb', 'Norsk bokmål'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('pt', 'Português'), ('pt-br', 'Português brasileiro'), ('ro', 'Română'), ('ru', 'Русский'), ('sk', 'Slovenčina'), ('sl', 'Slovenščina'), ('sq', 'Shqip'), ('sr', 'Српски'), ('sr-latn', 'Srpski'), ('sv', 'Svenska'), ('ta', 'தமிழ்'), ('th', 'ไทย'), ('tr', 'Türkçe'), ('uk', 'Українська'), ('zh-hans', '简体中文'), ('zh-hant', '正體中文'))
LANGUAGE_COOKIE_AGE = 12096000
LANGUAGE_COOKIE_HTTPONLY = True
LANGUAGE_COOKIE_SAMESITE = 'None'
LEGAL_INTEGRATION = None  ###
LEGAL_URL = None  ###
LICENSE_EXTRA = []  ###
LICENSE_FILTER = None  ###
LICENSE_REQUIRED = False  ###
LIMIT_TRANSLATION_LENGTH_BY_SOURCE_LENGTH = True  ###
LOCALE_FILTER_FILES = True  ###
LOCALIZE_CDN_PATH = None  ###
LOCALIZE_CDN_URL = None  ###
LOGGING = {'version': 1, 'disable_existing_loggers': True, 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}}, 'formatters': {'simple': {'format': '[%(asctime)s: %(levelname)s/%(process)s] %(message)s'}, 'logfile': {'format': '%(asctime)s %(levelname)s %(message)s'}, 'django.server': {'()': 'django.utils.log.ServerFormatter', 'format': '[%(server_time)s] %(message)s'}}, 'handlers': {'mail_admins': {'level': 'ERROR', 'filters': ['require_debug_false'], 'class': 'django.utils.log.AdminEmailHandler', 'include_html': True}, 'console': {'level': 'DEBUG', 'class': 'logging.StreamHandler', 'formatter': 'simple'}, 'django.server': {'level': 'INFO', 'class': 'logging.StreamHandler', 'formatter': 'django.server'}}, 'loggers': {'django.request': {'handlers': ['console', 'mail_admins'], 'level': 'ERROR', 'propagate': True}, 'django.server': {'handlers': ['django.server'], 'level': 'INFO', 'propagate': False}, 'django.db.backends': {'handlers': ['console'], 'level': 'CRITICAL'}, 'weblate': {'handlers': ['console'], 'level': 'INFO'}, 'weblate.vcs': {'handlers': ['console'], 'level': 'INFO'}, 'social': {'handlers': ['console'], 'level': 'INFO'}, 'django_auth_ldap': {'handlers': ['console'], 'level': 'INFO'}, 'djangosaml2idp': {'handlers': ['console'], 'level': 'INFO'}, 'fedora_messaging': {'handlers': ['console'], 'level': 'INFO'}}}
LOGIN_REDIRECT_URL = '/'
LOGIN_REQUIRED_URLS = []  ###
LOGIN_REQUIRED_URLS_EXCEPTIONS = ('{URL_PREFIX}/accounts/(.*)$', '{URL_PREFIX}/admin/login/(.*)$', '{URL_PREFIX}/static/(.*)$', '{URL_PREFIX}/widgets/(.*)$', '{URL_PREFIX}/data/(.*)$', '{URL_PREFIX}/hooks/(.*)$', '{URL_PREFIX}/healthz/$', '{URL_PREFIX}/api/(.*)$', '{URL_PREFIX}/js/i18n/$', '{URL_PREFIX}/contact/$', '{URL_PREFIX}/legal/(.*)$', '{URL_PREFIX}/avatar/(.*)$', '{URL_PREFIX}/site.webmanifest$')  ###
LOGOUT_URL = '/accounts/logout/'  ###
MANAGERS = (('Weblate Admin', 'admin@example.com'),)
MATOMO_SITE_ID = None  ###
MATOMO_URL = None  ###
MAXIMAL_PASSWORD_LENGTH = 72  ###
MEDIA_ROOT = '/app/data/media'
MEDIA_URL = '/media/'
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
MIDDLEWARE = ['weblate.middleware.RedirectMiddleware', 'weblate.middleware.ProxyMiddleware', 'corsheaders.middleware.CorsMiddleware', 'django.middleware.security.SecurityMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'weblate.accounts.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.clickjacking.XFrameOptionsMiddleware', 'social_django.middleware.SocialAuthExceptionMiddleware', 'weblate.api.middleware.ThrottlingMiddleware', 'weblate.middleware.SecurityMiddleware', 'weblate.wladmin.middleware.ManageMiddleware']
NEARBY_MESSAGES = 15  ###
OFFER_HOSTING = False  ###
OTP_WEBAUTHN_ALLOWED_ORIGINS = ['http://127.0.0.1:8090']  ###
OTP_WEBAUTHN_ALLOW_PASSWORDLESS_LOGIN = False  ###
OTP_WEBAUTHN_HELPER_CLASS = 'weblate.accounts.utils.WeblateWebAuthnHelper'  ###
OTP_WEBAUTHN_RP_ID = '127.0.0.1'  ###
OTP_WEBAUTHN_RP_NAME = 'Weblate'  ###
PAGURE_CREDENTIALS = {}  ###
PASSWORD_HASHERS = ['django.contrib.auth.hashers.Argon2PasswordHasher', 'django.contrib.auth.hashers.PBKDF2PasswordHasher', 'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher', 'django.contrib.auth.hashers.BCryptSHA256PasswordHasher']
PASSWORD_MINIMAL_STRENGTH = 3  ###
PRIVACY_URL = None  ###
PRIVATE_COMMIT_EMAIL_OPT_IN = True  ###
PRIVATE_COMMIT_EMAIL_TEMPLATE = '{username}@users.noreply.{site_domain}'  ###
PROJECT_BACKUP_KEEP_COUNT = 3  ###
PROJECT_BACKUP_KEEP_DAYS = 30  ###
PROJECT_NAME_RESTRICT_RE = None  ###
PROJECT_WEB_RESTRICT_HOST = {'localhost'}  ###
PROJECT_WEB_RESTRICT_NUMERIC = True  ###
PROJECT_WEB_RESTRICT_RE = None  ###
RATELIMIT_ATTEMPTS = 5  ###
RATELIMIT_COMMENT_ATTEMPTS = 30  ###
RATELIMIT_COMMENT_WINDOW = 60  ###
RATELIMIT_GLOSSARY_ATTEMPTS = 30  ###
RATELIMIT_GLOSSARY_WINDOW = 60  ###
RATELIMIT_LANGUAGE_ATTEMPTS = 2  ###
RATELIMIT_LANGUAGE_LOCKOUT = 600  ###
RATELIMIT_LANGUAGE_WINDOW = 300  ###
RATELIMIT_LOCKOUT = 600  ###
RATELIMIT_MESSAGE_ATTEMPTS = 2  ###
RATELIMIT_NOTIFICATION_LIMITS = [(3, 120), (10, 3600), (50, 86400)]  ###
RATELIMIT_PROJECT_ATTEMPTS = 5  ###
RATELIMIT_PROJECT_LOCKOUT = 600  ###
RATELIMIT_PROJECT_WINDOW = 600  ###
RATELIMIT_SEARCH_ATTEMPTS = 30  ###
RATELIMIT_SEARCH_LOCKOUT = 60  ###
RATELIMIT_SEARCH_WINDOW = 60  ###
RATELIMIT_TRANSLATE_ATTEMPTS = 30  ###
RATELIMIT_TRANSLATE_WINDOW = 60  ###
RATELIMIT_TRIAL_ATTEMPTS = 1  ###
RATELIMIT_TRIAL_LOCKOUT = 600  ###
RATELIMIT_TRIAL_WINDOW = 60  ###
RATELIMIT_WINDOW = 300  ###
REDIS_URL = 'redis://cache:6379/1'  ###
REGISTRATION_ALLOW_BACKENDS = []  ###
REGISTRATION_CAPTCHA = True  ###
REGISTRATION_EMAIL_MATCH = '.*'  ###
REGISTRATION_HINTS = {}  ###
REGISTRATION_OPEN = True  ###
REGISTRATION_REBIND = False  ###
REPOSITORY_ALERT_THRESHOLD = 25  ###
REQUIRE_LOGIN = False  ###
REST_FRAMEWORK = {'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticatedOrReadOnly'], 'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework.authentication.TokenAuthentication', 'weblate.api.authentication.BearerAuthentication', 'rest_framework.authentication.SessionAuthentication'), 'DEFAULT_THROTTLE_CLASSES': ('weblate.api.throttling.UserRateThrottle', 'weblate.api.throttling.AnonRateThrottle'), 'DEFAULT_THROTTLE_RATES': {'anon': '100/day', 'user': '5000/hour'}, 'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer', 'weblate.api.renderers.AutoCSVRenderer'], 'DEFAULT_PAGINATION_CLASS': 'weblate.api.pagination.StandardPagination', 'PAGE_SIZE': 50, 'VIEW_DESCRIPTION_FUNCTION': 'weblate.api.views.get_view_description', 'EXCEPTION_HANDLER': 'drf_standardized_errors.handler.exception_handler', 'UNAUTHENTICATED_USER': 'weblate.auth.models.get_anonymous', 'DEFAULT_SCHEMA_CLASS': 'weblate.api.generators.WeblateAutoSchema'}  ###
ROLLBAR_KEY = None  ###
ROOT_URLCONF = 'weblate.urls'  ###
SECRET_KEY = 'h0aJ8tuT8a2g5VO8HESsAtRSCVRZa5H56g4re8jjC1PSvEBgLF\n'
SECURE_BROWSER_XSS_FILTER = True  ###
SECURE_REDIRECT_EXEMPT = ('healthz/$',)
SECURE_SSL_HOST = '127.0.0.1:8090'
SENTRY_DSN = None  ###
SENTRY_ENVIRONMENT = '127.0.0.1:8090'  ###
SENTRY_EXTRA_ARGS = {}  ###
SENTRY_MONITOR_BEAT_TASKS = True  ###
SENTRY_PROFILES_SAMPLE_RATE = 1.0  ###
SENTRY_PROJECTS = ['weblate']  ###
SENTRY_RELEASES_API_URL = 'https://sentry.io/api/0/organizations/4507304895905792/releases/'  ###
SENTRY_SECURITY = None  ###
SENTRY_SEND_PII = False  ###
SENTRY_TOKEN = None  ###
SENTRY_TRACES_SAMPLE_RATE = 0.0  ###
SERVER_EMAIL = 'weblate@example.com'
SESSION_COOKIE_AGE = 1000
SESSION_COOKIE_AGE_2FA = 180  ###
SESSION_COOKIE_AGE_AUTHENTICATED = 1209600  ###
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SETTINGS_MODULE = 'weblate.settings_docker'  ###
SILENCED_SYSTEM_CHECKS = ['admin.E408', 'auth.E013', 'drf_spectacular.W001', 'drf_spectacular.W002', 'otp_webauthn.E031']
SIMILAR_MESSAGES = 5  ###
SIMPLIFY_LANGUAGES = True  ###
SINGLE_PROJECT = False  ###
SITE_DOMAIN = '127.0.0.1:8090'  ###
SITE_ID = 1  ###
SITE_TITLE = 'Weblate'  ###
SITE_URL = 'http://127.0.0.1:8090'  ###
SOCIAL_AUTH_AUTH0_IMAGE = 'auth0.svg'  ###
SOCIAL_AUTH_AUTH0_KEY = None  ###
SOCIAL_AUTH_AUTH0_TITLE = 'Auth0'  ###
SOCIAL_AUTH_AZUREAD_OAUTH2_KEY = None  ###
SOCIAL_AUTH_AZUREAD_TENANT_OAUTH2_KEY = None  ###
SOCIAL_AUTH_BITBUCKET_OAUTH2_KEY = None  ###
SOCIAL_AUTH_DISCONNECT_PIPELINE = ('social_core.pipeline.disconnect.allowed_to_disconnect', 'social_core.pipeline.disconnect.get_entries', 'social_core.pipeline.disconnect.revoke_tokens', 'weblate.accounts.pipeline.cycle_session', 'weblate.accounts.pipeline.adjust_primary_mail', 'weblate.accounts.pipeline.notify_disconnect', 'social_core.pipeline.disconnect.disconnect', 'weblate.accounts.pipeline.cleanup_next')  ###
SOCIAL_AUTH_EMAIL_FORM_URL = '/accounts/email/'  ###
SOCIAL_AUTH_EMAIL_VALIDATION_FUNCTION = 'weblate.accounts.pipeline.send_validation'  ###
SOCIAL_AUTH_EMAIL_VALIDATION_URL = '/accounts/email-sent/'  ###
SOCIAL_AUTH_FACEBOOK_KEY = None  ###
SOCIAL_AUTH_FEDORA_OIDC_KEY = None  ###
SOCIAL_AUTH_GITEA_KEY = None  ###
SOCIAL_AUTH_GITHUB_ENTERPRISE_KEY = None  ###
SOCIAL_AUTH_GITHUB_KEY = None  ###
SOCIAL_AUTH_GITHUB_ORG_NAME = None  ###
SOCIAL_AUTH_GITHUB_TEAM_ID = None  ###
SOCIAL_AUTH_GITLAB_KEY = None  ###
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = None  ###
SOCIAL_AUTH_KEYCLOAK_KEY = None  ###
SOCIAL_AUTH_LOGIN_ERROR_URL = '/accounts/login/'  ###
SOCIAL_AUTH_MUSICBRAINZ_KEY = None  ###
SOCIAL_AUTH_NEW_ASSOCIATION_REDIRECT_URL = '/accounts/profile/#account'  ###
SOCIAL_AUTH_OIDC_OIDC_ENDPOINT = None  ###
SOCIAL_AUTH_PIPELINE = ['social_core.pipeline.social_auth.social_details', 'social_core.pipeline.social_auth.social_uid', 'social_core.pipeline.social_auth.auth_allowed', 'social_core.pipeline.social_auth.social_user', 'weblate.accounts.pipeline.store_params', 'weblate.accounts.pipeline.verify_open', 'social_core.pipeline.user.get_username', 'weblate.accounts.pipeline.require_email', 'social_core.pipeline.mail.mail_validation', 'weblate.accounts.pipeline.revoke_mail_code', 'weblate.accounts.pipeline.ensure_valid', 'weblate.accounts.pipeline.remove_account', 'social_core.pipeline.social_auth.associate_by_email', 'weblate.accounts.pipeline.reauthenticate', 'weblate.accounts.pipeline.verify_username', 'social_core.pipeline.user.create_user', 'social_core.pipeline.social_auth.associate_user', 'social_core.pipeline.social_auth.load_extra_data', 'weblate.accounts.pipeline.second_factor', 'weblate.accounts.pipeline.cleanup_next', 'weblate.accounts.pipeline.user_full_name', 'weblate.accounts.pipeline.store_email', 'weblate.accounts.pipeline.notify_connect', 'weblate.accounts.pipeline.handle_invite', 'weblate.accounts.pipeline.password_reset']  ###
SOCIAL_AUTH_PROTECTED_USER_FIELDS = ('email',)  ###
SOCIAL_AUTH_RAISE_EXCEPTIONS = True  ###
SOCIAL_AUTH_REDIRECT_IS_HTTPS = False  ###
SOCIAL_AUTH_SAML_IMAGE = 'saml.svg'  ###
SOCIAL_AUTH_SAML_TITLE = 'SAML'  ###
SOCIAL_AUTH_SLACK_KEY = None  ###
SOCIAL_AUTH_SLUGIFY_FUNCTION = 'weblate.accounts.pipeline.slugify_username'  ###
SOCIAL_AUTH_SLUGIFY_USERNAMES = True  ###
SOCIAL_AUTH_STRATEGY = 'weblate.accounts.strategy.WeblateStrategy'  ###
SOCIAL_AUTH_USER_AGENT = 'Weblate/5.15.1'  ###
SPECIAL_CHARS = ('\t', '\n', '\xa0', '…')  ###
SPECTACULAR_SETTINGS = {'REDOC_DIST': 'SIDECAR', 'REDOC_UI_SETTINGS': {'theme': {'typography': {'fontFamily': '"Source Sans 3", sans-serif', 'headings': {'fontFamily': '"Source Sans 3", sans-serif'}, 'code': {'fontFamily': '"Source Code Pro", monospace'}}, 'logo': {'maxWidth': '150px', 'maxHeight': '50vh', 'margin': 'auto'}}}, 'SWAGGER_UI_DIST': 'SIDECAR', 'DEFAULT_GENERATOR_CLASS': 'weblate.api.generators.WeblateSchemaGenerator', 'OAS_VERSION': '3.1.1', 'SERVERS': [{'url': 'http://127.0.0.1:8090', 'description': 'Weblate'}], 'SERVE_URLCONF': 'weblate.urls', 'TITLE': "Weblate's REST API", 'LICENSE': {'name': 'GNU General Public License v3 or later', 'url': 'https://docs.weblate.org/en/weblate-5.15.1/contributing/license.html'}, 'DESCRIPTION': '\nThe API is accessible on the ``/api/`` URL and it is based on [Django REST framework](https://www.django-rest-framework.org/).\n\nThe OpenAPI specification is available as feature preview, feedback welcome!\n\n## Authorization\n\n<!-- Redoc-Inject: <security-definitions> -->\n\n\n    ', 'EXTENSIONS_INFO': {'x-logo': {'url': '/static/weblate.svg'}}, 'VERSION': None, 'ENUM_NAME_OVERRIDES': {'ColorEnum': 'weblate.utils.colors.ColorChoices.choices', 'ValidationErrorEnum': 'drf_standardized_errors.openapi_serializers.ValidationErrorEnum.choices', 'ClientErrorEnum': 'drf_standardized_errors.openapi_serializers.ClientErrorEnum.choices', 'ServerErrorEnum': 'drf_standardized_errors.openapi_serializers.ServerErrorEnum.choices', 'ErrorCode401Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode401Enum.choices', 'ErrorCode403Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode403Enum.choices', 'ErrorCode404Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode404Enum.choices', 'ErrorCode405Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode405Enum.choices', 'ErrorCode406Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode406Enum.choices', 'ErrorCode415Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode415Enum.choices', 'ErrorCode429Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode429Enum.choices', 'ErrorCode500Enum': 'drf_standardized_errors.openapi_serializers.ErrorCode500Enum.choices', 'ErrorCode423Enum': 'weblate.api.serializers.ErrorCode423Enum.choices'}, 'POSTPROCESSING_HOOKS': ['drf_standardized_errors.openapi_hooks.postprocess_schema_enums', 'weblate.api.docs.add_middleware_headers'], 'EXTERNAL_DOCS': {'url': 'https://docs.weblate.org/en/weblate-5.15.1/index.html', 'description': 'Official Weblate documentation'}, 'TAGS': [{'name': 'root', 'description': 'The API root entry point.'}, {'name': 'users', 'description': 'Added in version 4.0.'}, {'name': 'groups', 'description': 'Added in version 4.0.'}, {'name': 'roles'}, {'name': 'languages'}, {'name': 'projects'}, {'name': 'components'}, {'name': 'translations'}, {'name': 'memory', 'description': 'Added in version 4.14.'}, {'name': 'units', 'description': 'A unit is a single piece of a translation which pairs a source string with a corresponding translated string and also contains some related metadata. The term is derived from the Translate Toolkit and XLIFF.'}, {'name': 'changes'}, {'name': 'screenshots'}, {'name': 'addons', 'description': 'Added in version 4.4.1.'}, {'name': 'component-lists', 'description': 'Added in version 4.0.'}, {'name': 'glossary', 'description': '**Changed in version 4.5:** Glossaries are now stored as regular components, translations and strings, please use respective API instead.'}, {'name': 'tasks', 'description': 'Added in version 4.4.\n\nListing of the tasks is currently not available.'}, {'name': 'statistics', 'description': 'Many endpoints support displaying statistics for their objects.'}, {'name': 'metrics'}, {'name': 'search', 'description': 'Added in version 4.18.'}, {'name': 'categories'}, {'name': 'hooks', 'description': 'Notification hooks allow external applications to notify Weblate that the VCS repository has been updated.\n\nYou can use repository endpoints for projects, components and translations to update individual repositories.'}, {'name': 'exports', 'description': 'Weblate provides various exports to allow you to further process the data.'}, {'name': 'rssFeeds', 'description': 'Changes in translations are exported in RSS feeds.'}, {'name': 'webhooks', 'description': 'Notifications sent by Weblate.'}], 'WEBHOOKS': ['weblate.addons.webhooks.change_event_webhook']}  ###
SSH_EXTRA_ARGS = ''  ###
STATICFILES_DIRS = ()
STATICFILES_FINDERS = ('django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder', 'compressor.finders.CompressorFinder')
STATIC_ROOT = '/app/cache/static'
STATIC_URL = '/static/'
STATS_LAZY = False  ###
STATUS_URL = None  ###
SUGGESTION_CLEANUP_DAYS = None  ###
SUPPORT_API_URL = 'https://weblate.org/api/support/'  ###
SUPPORT_STATUS_CHECK = False  ###
TEMPLATES = [{'BACKEND': 'django.template.backends.django.DjangoTemplates', 'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth', 'django.template.context_processors.debug', 'django.template.context_processors.i18n', 'django.template.context_processors.request', 'django.template.context_processors.csrf', 'django.contrib.messages.context_processors.messages', 'weblate.trans.context_processors.weblate_context']}, 'APP_DIRS': True}]
TIME_ZONE = 'UTC'
UNUSED_ALERT_DAYS = 365  ###
UPDATE_LANGUAGES = True  ###
URL_PREFIX = ''  ###
VAT_RATE = 1.21  ###
VCS_ALLOW_HOSTS = set()  ###
VCS_ALLOW_SCHEMES = {'https', 'ssh'}  ###
VCS_API_DELAY = 10  ###
VCS_API_TIMEOUT = 10  ###
VCS_BACKENDS = ('weblate.vcs.git.GitRepository', 'weblate.vcs.git.GitWithGerritRepository', 'weblate.vcs.git.SubversionRepository', 'weblate.vcs.git.GithubRepository', 'weblate.vcs.git.AzureDevOpsRepository', 'weblate.vcs.git.GiteaRepository', 'weblate.vcs.git.GitLabRepository', 'weblate.vcs.git.PagureRepository', 'weblate.vcs.git.LocalRepository', 'weblate.vcs.git.GitForcePushRepository', 'weblate.vcs.git.BitbucketServerRepository', 'weblate.vcs.git.BitbucketCloudRepository', 'weblate.vcs.mercurial.HgRepository')  ###
VCS_CLONE_DEPTH = 1  ###
WEBLATE_ADDONS = ['weblate.addons.gettext.GenerateMoAddon', 'weblate.addons.gettext.UpdateLinguasAddon', 'weblate.addons.gettext.UpdateConfigureAddon', 'weblate.addons.gettext.MsgmergeAddon', 'weblate.addons.gettext.GettextAuthorComments', 'weblate.addons.cleanup.CleanupAddon', 'weblate.addons.cleanup.RemoveBlankAddon', 'weblate.addons.consistency.LanguageConsistencyAddon', 'weblate.addons.discovery.DiscoveryAddon', 'weblate.addons.autotranslate.AutoTranslateAddon', 'weblate.addons.flags.SourceEditAddon', 'weblate.addons.flags.TargetEditAddon', 'weblate.addons.flags.SameEditAddon', 'weblate.addons.flags.BulkEditAddon', 'weblate.addons.flags.TargetRepoUpdateAddon', 'weblate.addons.generate.GenerateFileAddon', 'weblate.addons.generate.PseudolocaleAddon', 'weblate.addons.generate.PrefillAddon', 'weblate.addons.generate.FillReadOnlyAddon', 'weblate.addons.properties.PropertiesSortAddon', 'weblate.addons.git.GitSquashAddon', 'weblate.addons.removal.RemoveComments', 'weblate.addons.removal.RemoveSuggestions', 'weblate.addons.resx.ResxUpdateAddon', 'weblate.addons.cdn.CDNJSAddon', 'weblate.addons.webhooks.WebhookAddon', 'weblate.addons.webhooks.SlackWebhookAddon', 'weblate.addons.fedora_messaging.FedoraMessagingAddon']  ###
WEBLATE_EXPORTERS = ('weblate.formats.exporters.PoExporter', 'weblate.formats.exporters.PoXliffExporter', 'weblate.formats.exporters.XliffExporter', 'weblate.formats.exporters.TBXExporter', 'weblate.formats.exporters.TMXExporter', 'weblate.formats.exporters.MoExporter', 'weblate.formats.exporters.CSVExporter', 'weblate.formats.exporters.MultiCSVExporter', 'weblate.formats.exporters.XlsxExporter', 'weblate.formats.exporters.JSONExporter', 'weblate.formats.exporters.JSONNestedExporter', 'weblate.formats.exporters.AndroidResourceExporter', 'weblate.formats.exporters.StringsExporter')  ###
WEBLATE_FORMATS = ('weblate.formats.ttkit.PoFormat', 'weblate.formats.ttkit.PoMonoFormat', 'weblate.formats.ttkit.TSFormat', 'weblate.formats.ttkit.XliffFormat', 'weblate.formats.ttkit.RichXliffFormat', 'weblate.formats.ttkit.Xliff2Format', 'weblate.formats.ttkit.RichXliff2Format', 'weblate.formats.ttkit.PoXliffFormat', 'weblate.formats.ttkit.StringsFormat', 'weblate.formats.ttkit.StringsUtf8Format', 'weblate.formats.ttkit.PropertiesUtf8Format', 'weblate.formats.ttkit.PropertiesUtf16Format', 'weblate.formats.ttkit.PropertiesFormat', 'weblate.formats.ttkit.JoomlaFormat', 'weblate.formats.ttkit.GWTFormat', 'weblate.formats.ttkit.GWTISOFormat', 'weblate.formats.ttkit.PhpFormat', 'weblate.formats.ttkit.LaravelPhpFormat', 'weblate.formats.ttkit.RESXFormat', 'weblate.formats.ttkit.AndroidFormat', 'weblate.formats.ttkit.MOKOFormat', 'weblate.formats.ttkit.CMPFormat', 'weblate.formats.ttkit.JSONFormat', 'weblate.formats.ttkit.JSONNestedFormat', 'weblate.formats.ttkit.WebExtensionJSONFormat', 'weblate.formats.ttkit.I18NextFormat', 'weblate.formats.ttkit.CatkeysFormat', 'weblate.formats.ttkit.I18NextV4Format', 'weblate.formats.ttkit.GoI18JSONFormat', 'weblate.formats.ttkit.GoI18V2JSONFormat', 'weblate.formats.ttkit.GoTextFormat', 'weblate.formats.ttkit.ARBFormat', 'weblate.formats.ttkit.FormatJSFormat', 'weblate.formats.ttkit.CSVFormat', 'weblate.formats.ttkit.CSVUtf8Format', 'weblate.formats.ttkit.CSVSimpleFormat', 'weblate.formats.ttkit.CSVUtf8SimpleFormat', 'weblate.formats.ttkit.CSVSimpleFormatISO', 'weblate.formats.ttkit.YAMLFormat', 'weblate.formats.ttkit.RubyYAMLFormat', 'weblate.formats.ttkit.SubRipFormat', 'weblate.formats.ttkit.MicroDVDFormat', 'weblate.formats.ttkit.AdvSubStationAlphaFormat', 'weblate.formats.ttkit.SubStationAlphaFormat', 'weblate.formats.ttkit.DTDFormat', 'weblate.formats.ttkit.FlatXMLFormat', 'weblate.formats.ttkit.ResourceDictionaryFormat', 'weblate.formats.ttkit.INIFormat', 'weblate.formats.ttkit.InnoSetupINIFormat', 'weblate.formats.ttkit.PropertiesMi18nFormat', 'weblate.formats.external.XlsxFormat', 'weblate.formats.txt.AppStoreFormat', 'weblate.formats.convert.HTMLFormat', 'weblate.formats.convert.IDMLFormat', 'weblate.formats.convert.OpenDocumentFormat', 'weblate.formats.convert.PlainTextFormat', 'weblate.formats.convert.DokuWikiFormat', 'weblate.formats.convert.MarkdownFormat', 'weblate.formats.convert.MediaWikiFormat', 'weblate.formats.convert.WindowsRCFormat', 'weblate.formats.ttkit.XWikiPropertiesFormat', 'weblate.formats.ttkit.XWikiPagePropertiesFormat', 'weblate.formats.ttkit.XWikiFullPageFormat', 'weblate.formats.ttkit.TBXFormat', 'weblate.formats.ttkit.StringsdictFormat', 'weblate.formats.ttkit.FluentFormat', 'weblate.formats.ttkit.GoI18nTOMLFormat', 'weblate.formats.ttkit.TOMLFormat', 'weblate.formats.ttkit.RESJSONFormat', 'weblate.formats.ttkit.NextcloudJSONFormat', 'weblate.formats.multi.MultiCSVUtf8Format')  ###
WEBLATE_GPG_ALGO = 'default'  ###
WEBLATE_GPG_IDENTITY = None  ###
WEBLATE_LOG_GELF_HOST = None  ###
WEBLATE_MACHINERY = ['weblate.machinery.apertium.ApertiumAPYTranslation', 'weblate.machinery.aws.AWSTranslation', 'weblate.machinery.alibaba.AlibabaTranslation', 'weblate.machinery.baidu.BaiduTranslation', 'weblate.machinery.deepl.DeepLTranslation', 'weblate.machinery.glosbe.GlosbeTranslation', 'weblate.machinery.google.GoogleTranslation', 'weblate.machinery.googlev3.GoogleV3Translation', 'weblate.machinery.libretranslate.LibreTranslateTranslation', 'weblate.machinery.microsoft.MicrosoftCognitiveTranslation', 'weblate.machinery.modernmt.ModernMTTranslation', 'weblate.machinery.mymemory.MyMemoryTranslation', 'weblate.machinery.netease.NeteaseSightTranslation', 'weblate.machinery.tmserver.TMServerTranslation', 'weblate.machinery.yandex.YandexTranslation', 'weblate.machinery.yandexv2.YandexV2Translation', 'weblate.machinery.saptranslationhub.SAPTranslationHub', 'weblate.machinery.youdao.YoudaoTranslation', 'weblate.machinery.systran.SystranTranslation', 'weblate.machinery.openai.OpenAITranslation', 'weblate.machinery.openai.AzureOpenAITranslation', 'weblate.machinery.ollama.OllamaTranslation', 'weblate.machinery.weblatetm.WeblateTranslation', 'weblate.memory.machine.WeblateMemory', 'weblate.machinery.cyrtranslit.CyrTranslitTranslation']  ###
WEBLATE_SAML_IDP = None  ###
WEBLATE_SECURE_PROXY_SSL_HEADER = []  ###
WEBSITE_REQUIRED = True  ###
ZAMMAD_URL = None  ###