import type { Metadata } from "next";
import Link from "next/link";
import type { ComponentType } from "react";

import type { SupportedLocale } from "@/config/site";
import { isSupportedLocale } from "@/lib/i18n-utils";
import { buildLocalizedPath } from "@/lib/locale-links";
import type { Locale } from "@/i18n-config";
import { i18n } from "@/i18n-config";
import { Button } from "@/components/ui/button";
import {
  Anchor,
  ArrowUpRight,
  BadgeCheck,
  BarChart3,
  Globe2,
  Layers,
  Map,
  Radar,
  ShieldCheck,
  Sparkles
} from "lucide-react";
import {
  AirplaneTilt,
  Bank,
  CurrencyCircleDollar,
  Storefront,
  Truck
} from "@phosphor-icons/react/dist/ssr";

export const dynamic = "force-static";

type IconType = ComponentType<{ className?: string }>;

type Metric = {
  title: string;
  caption: string;
  description: string;
  icon: IconType;
};

type LocalChannel = {
  name: string;
  focus: string;
  details: string;
  icon: IconType;
};

type Step = {
  phase: string;
  title: string;
  description: string;
  bullets: string[];
  icon: IconType;
};

type FAQItem = {
  question: string;
  answer: string;
};

const METRICS: Metric[] = [
  {
    title: "Global PSP bundle",
    caption: "7 gateways orchestrated",
    description:
      "PayPal, Amazon Pay, PayU, Stripe, Authorize.Net, Braintree, and Adyen—exactly what the legacy Yemen page listed—operate inside one AI-supervised control plane.",
    icon: Bank
  },
  {
    title: "Yemen-first experiences",
    caption: "Localized trust",
    description:
      "Copy, UX patterns, and approvals reference People’s Democratic Republic of Yemen – YE regulatory language while respecting regional sensitivities.",
    icon: Anchor
  },
  {
    title: "AI intelligence",
    caption: "24/7 insight briefs",
    description:
      "AI monitors conversion, settlement timing, FX exposure, and distributor sentiment so leadership intervenes before friction escalates.",
    icon: Sparkles
  }
];

const LOCAL_CHANNELS: LocalChannel[] = [
  {
    name: "Yemeni banking & hawala partners",
    focus: "Treasury & payout discipline",
    details:
      "Synchronise PSP batches with local banks and hawala networks, manage multi-currency flows, and export audit-ready ledgers.",
    icon: CurrencyCircleDollar
  },
  {
    name: "Mobile wallets & telecom rails",
    focus: "Everyday accessibility",
    details:
      "Integrate MTN, Sabafon, and other telecom-led wallets with QR and USSD journeys while keeping security and compliance intact.",
    icon: Storefront
  },
  {
    name: "Logistics & field distribution",
    focus: "Resilient delivery",
    details:
      "AI tracks inventory and delivery status across challenging logistics routes, surfacing alerts when replenishment or support is needed.",
    icon: Truck
  },
  {
    name: "Diaspora & cross-border corridors",
    focus: "Remittance-ready experiences",
    details:
      "Blend global PSPs with remittance-friendly options so diaspora-backed purchases and distributor payouts remain predictable.",
    icon: AirplaneTilt
  }
];

const STEPS: Step[] = [
  {
    phase: "01",
    title: "Discovery & compliance alignment",
    description:
      "Workshops with finance, compliance, and field leaders uncover today’s workflows and regulatory commitments.",
    bullets: [
      "Audit of PayPal, Amazon Pay, PayU, Stripe, Authorize.Net, Braintree, and Adyen usage",
      "Regulatory inventory covering central bank directives and partner obligations",
      "Mapping of distributor journeys across urban, rural, and diaspora-supported regions"
    ],
    icon: Globe2
  },
  {
    phase: "02",
    title: "Experience design & enablement",
    description:
      "Prototype bilingual flows referencing People’s Democratic Republic of Yemen language with AI-authored microcopy.",
    bullets: [
      "Checkout variants for mobile wallets, card payments, cash-to-digital, and remittance inputs",
      "Payout approvals, maker-checker flows, and document vaults for governance",
      "Training packs for finance, compliance, and field teams with AI-generated summaries"
    ],
    icon: BadgeCheck
  },
  {
    phase: "03",
    title: "Pilot & telemetry",
    description:
      "Launch with AI dashboards covering conversion, settlements, FX drift, and distributor sentiment.",
    bullets: [
      "Variance analysis between PSP reports, banks, and hawala records",
      "Alerts for chargeback spikes, policy updates, or supply-chain disruptions",
      "Hypercare rituals translating insight into daily actions"
    ],
    icon: Radar
  },
  {
    phase: "04",
    title: "Scale & optimisation",
    description:
      "Expand to new territories, product lines, and partnerships while AI keeps leadership aligned.",
    bullets: [
      "Quarterly optimisation sprints prioritised with finance and operations leaders",
      "Scenario planning for neighbouring markets and diaspora-support programmes",
      "Executive summaries auto-generated by AI with recommended actions"
    ],
    icon: Layers
  }
];

const FAQ_ITEMS: FAQItem[] = [
  {
    question: "Which payment gateways are orchestrated for Yemen?",
    answer:
      "Cloud MLM Software unifies PayPal, Amazon Pay, PayU, Stripe, Authorize.Net, Braintree, and Adyen—preserving the legacy list—while layering in hawala, banking, and telecom-led rails popular in Yemen."
  },
  {
    question: "How do you maintain compliance amid shifting regulations?",
    answer:
      "We embed AML screening, sanctions checks, maker-checker approvals, and document vaults tailored to Yemeni regulations and international partner expectations."
  },
  {
    question: "Can AI really support teams operating in complex conditions?",
    answer:
      "Yes. AI forecasts settlement delays, inventory gaps, and distributor sentiment shifts, helping leaders adjust incentives, logistics, and communications proactively."
  }
];

export async function generateMetadata({
  params
}: {
  params: { lang: SupportedLocale } | Promise<{ lang: SupportedLocale }>;
}): Promise<Metadata> {
  const resolved = params instanceof Promise ? await params : params;
  const locale = resolveLocale(resolved?.lang ?? "en");
  const title = "Yemen MLM Payment Gateways | Cloud MLM Software";
  const description =
    "Deliver resilient MLM payments in Yemen with Cloud MLM Software. Unite PayPal, Amazon Pay, PayU, Stripe, Authorize.Net, Braintree, Adyen, and local partners under AI supervision.";

  return {
    title,
    description,
    alternates: {
      canonical: buildLocalizedPath("/mlm-software-payment-gateways/yemen", locale)
    },
    openGraph: {
      title,
      description
    },
    twitter: {
      title,
      description
    }
  };
}

type YemenPaymentGatewaysPageProps = {
  params: { lang: SupportedLocale } | Promise<{ lang: SupportedLocale }>;
};

export default async function YemenPaymentGatewaysPage({ params }: YemenPaymentGatewaysPageProps) {
  const resolved = params instanceof Promise ? await params : params;
  const locale = resolveLocale(resolved?.lang ?? "en");
  const contactHref = buildLocalizedPath("/contact", locale);
  const demoHref = buildLocalizedPath("/free-mlm-software-demo", locale);
  const pricingHref = buildLocalizedPath("/pricing", locale);
  const gatewaysHref = buildLocalizedPath("/mlm-software-payment-gateways", locale);

  return (
    <div className="space-y-24 pb-24">
      <section className="relative isolate overflow-hidden rounded-[3rem] border border-orange-200/70 bg-gradient-to-br from-orange-50 via-white to-rose-100 px-6 py-20 shadow-sm dark:border-orange-500/40 dark:from-slate-950 dark:via-slate-920 dark:to-slate-900 sm:px-16">
        <div className="pointer-events-none absolute inset-0 -z-10 bg-[radial-gradient(circle_at_12%_12%,rgba(251,146,60,0.3),transparent_55%),radial-gradient(circle_at_82%_18%,rgba(244,114,182,0.28),transparent_55%),radial-gradient(circle_at_45%_85%,rgba(37,99,235,0.22),transparent_60%)] dark:bg-[radial-gradient(circle_at_12%_12%,rgba(251,146,60,0.35),transparent_60%),radial-gradient(circle_at_82%_18%,rgba(244,114,182,0.33),transparent_55%),radial-gradient(circle_at_45%_82%,rgba(37,99,235,0.28),transparent_60%)]" />
        <div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[minmax(0,1fr)_minmax(0,0.85fr)] lg:items-center">
          <div className="space-y-8 text-slate-900 dark:text-slate-100">
            <span className="inline-flex items-center gap-2 rounded-full border border-orange-200/80 bg-white/80 px-4 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-orange-700 dark:border-orange-400/40 dark:bg-slate-900/70 dark:text-orange-200">
              <ShieldCheck className="h-4 w-4" aria-hidden />
              Yemen payment gateways
            </span>
            <div className="space-y-6">
              <h1 className="text-balance text-4xl font-semibold tracking-tight sm:text-5xl">
                Resilient MLM payments for Yemen’s growth journey
              </h1>
              <p className="text-lg text-slate-700 dark:text-slate-300">
                Ways to accept payments from MLM Software in People’s Democratic Republic of Yemen – YE now
                run through Cloud MLM Software’s AI-guided operating model. We keep the legacy gateways intact
                while adapting to local banking, hawala, telecom wallets, and diaspora corridors.
              </p>
            </div>
            <div className="grid gap-4 sm:grid-cols-3">
              {METRICS.map((metric) => (
                <article
                  key={metric.title}
                  className="rounded-3xl border border-orange-100/80 bg-white/80 p-6 shadow-sm dark:border-slate-700/60 dark:bg-slate-900/60"
                >
                  <metric.icon className="h-6 w-6 text-orange-600 dark:text-orange-300" aria-hidden />
                  <p className="mt-2 text-xs font-semibold uppercase tracking-[0.2em] text-orange-700 dark:text-orange-200">
                    {metric.caption}
                  </p>
                  <h2 className="mt-3 text-lg font-semibold text-slate-900 dark:text-white">
                    {metric.title}
                  </h2>
                  <p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{metric.description}</p>
                </article>
              ))}
            </div>
            <div className="flex flex-wrap gap-4">
              <Button
                asChild
                size="lg"
                className="gap-2 bg-orange-600 text-white hover:bg-orange-500 dark:bg-orange-500 dark:hover:bg-orange-400"
              >
                <Link href={contactHref}>
                  Talk with a Yemen payments architect
                  <ArrowUpRight className="h-4 w-4" aria-hidden />
                </Link>
              </Button>
              <Button
                asChild
                size="lg"
                variant="outline"
                className="border-orange-200/80 text-orange-800 hover:bg-white/70 dark:border-orange-400/40 dark:text-orange-200 dark:hover:bg-slate-900/70"
              >
                <Link href={demoHref}>See Cloud MLM Software in action</Link>
              </Button>
            </div>
          </div>
          <aside className="rounded-[2.75rem] border border-white/60 bg-white/85 p-8 shadow-lg backdrop-blur-lg dark:border-slate-700/60 dark:bg-slate-900/70">
            <div className="space-y-6">
              <article className="rounded-3xl border border-orange-100/80 bg-white/80 p-6 shadow-sm dark:border-slate-700/60 dark:bg-slate-900/60">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-700 dark:text-orange-200">
                  Gateway bundle
                </p>
                <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">
                  PayPal · Amazon Pay · PayU · Stripe · Authorize.Net · Braintree · Adyen
                </p>
              </article>
              <article className="rounded-3xl border border-orange-100/80 bg-white/80 p-6 shadow-sm dark:border-slate-700/60 dark:bg-slate-900/60">
                <p className="text-xs font-semibold uppercase tracking-[0.2em] text-orange-700 dark:text-orange-200">
                  AI observability
                </p>
                <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">
                  AI copilots track conversion, settlement timing, supply-chain health, and distributor sentiment to keep leadership informed.
                </p>
              </article>
              <Button
                asChild
                size="lg"
                className="w-full gap-2 bg-slate-900 text-white hover:bg-slate-800 dark:bg-orange-500 dark:hover:bg-orange-400"
              >
                <Link href={pricingHref}>
                  Review Yemen implementation packs
                  <ArrowUpRight className="h-4 w-4" aria-hidden />
                </Link>
              </Button>
            </div>
          </aside>
        </div>
      </section>

      <section className="container space-y-12">
        <div className="max-w-3xl space-y-4">
          <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-slate-700 dark:border-slate-700 dark:text-slate-200">
            <BarChart3 className="h-4 w-4" aria-hidden />
            Local payment fabric
          </span>
          <h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">
            Blend global PSPs with Yemen’s economic infrastructure
          </h2>
        </div>
        <div className="grid gap-6 lg:grid-cols-2">
          {LOCAL_CHANNELS.map((channel) => (
            <article
              key={channel.name}
              className="flex h-full flex-col gap-4 rounded-3xl border border-orange-100/80 bg-white/85 p-8 shadow-sm dark:border-slate-700/60 dark:bg-slate-900/60"
            >
              <channel.icon className="h-6 w-6 text-orange-600 dark:text-orange-300" aria-hidden />
              <div>
                <h3 className="text-xl font-semibold text-slate-900 dark:text-white">{channel.name}</h3>
                <p className="text-sm font-medium text-orange-700 dark:text-orange-200">{channel.focus}</p>
              </div>
              <p className="text-sm text-slate-600 dark:text-slate-300">{channel.details}</p>
            </article>
          ))}
        </div>
      </section>

      <section className="container space-y-12">
        <div className="max-w-3xl space-y-4">
          <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-slate-700 dark:border-slate-700 dark:text-slate-200">
            <Map className="h-4 w-4" aria-hidden />
            Execution path
          </span>
          <h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">
            Four steps to Yemen-wide resilience and growth
          </h2>
        </div>
        <div className="grid gap-6 lg:grid-cols-2">
          {STEPS.map((step) => (
            <article
              key={step.phase}
              className="flex h-full flex-col gap-4 rounded-3xl border border-slate-200/70 bg-white/85 p-8 shadow-sm dark:border-slate-700/60 dark:bg-slate-900/60"
            >
              <div className="flex items-start gap-3">
                <span className="flex h-10 w-10 items-center justify-center rounded-full border border-slate-200 bg-white text-base font-semibold text-slate-700 dark:border-slate-700 dark:bg-slate-900/60 dark:text-slate-200">
                  {step.phase}
                </span>
                <div>
                  <step.icon className="h-5 w-5 text-slate-700 dark:text-slate-200" aria-hidden />
                  <h3 className="mt-3 text-xl font-semibold text-slate-900 dark:text-white">{step.title}</h3>
                </div>
              </div>
              <p className="text-sm text-slate-600 dark:text-slate-300">{step.description}</p>
              <ul className="space-y-3 text-sm text-slate-600 dark:text-slate-300">
                {step.bullets.map((bullet) => (
                  <li key={bullet} className="flex items-start gap-2">
                    <ArrowUpRight className="mt-1 h-3.5 w-3.5 text-slate-500 dark:text-slate-300" aria-hidden />
                    <span>{bullet}</span>
                  </li>
                ))}
              </ul>
            </article>
          ))}
        </div>
      </section>

      <section className="container space-y-10">
        <div className="max-w-3xl space-y-4">
          <span className="inline-flex items-center gap-2 rounded-full border border-slate-200 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-slate-700 dark:border-slate-700 dark:text-slate-200">
            <Sparkles className="h-4 w-4" aria-hidden />
            Leadership questions
          </span>
          <h2 className="text-balance text-3xl font-semibold tracking-tight sm:text-4xl">
            AI-prepared answers for Yemen finance and compliance teams
          </h2>
        </div>
        <div className="grid gap-6 lg:grid-cols-3">
          {FAQ_ITEMS.map((item) => (
            <article
              key={item.question}
              className="flex h-full flex-col gap-3 rounded-3xl border border-slate-200/70 bg-white/85 p-6 shadow-sm dark:border-slate-700/60 dark:bg-slate-900/60"
            >
              <h3 className="text-lg font-semibold text-slate-900 dark:text-white">{item.question}</h3>
              <p className="text-sm text-slate-600 dark:text-slate-300">{item.answer}</p>
            </article>
          ))}
        </div>
        <div className="flex flex-wrap gap-4">
          <Button
            asChild
            size="lg"
            className="gap-2 bg-slate-900 text-white hover:bg-slate-800 dark:bg-orange-500 dark:hover:bg-orange-400"
          >
            <Link href={contactHref}>
              Build your Yemen launch plan
              <ArrowUpRight className="h-4 w-4" aria-hidden />
            </Link>
          </Button>
          <Button
            asChild
            size="lg"
            variant="outline"
            className="border-slate-200 text-slate-800 hover:bg-white/70 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-900/70"
          >
            <Link href={pricingHref}>Compare implementation packages</Link>
          </Button>
          <Button
            asChild
            size="lg"
            variant="outline"
            className="border-slate-200 text-slate-800 hover:bg-white/70 dark:border-slate-700 dark:text-slate-200 dark:hover:bg-slate-900/70"
          >
            <Link href={gatewaysHref}>Explore global payment gateways</Link>
          </Button>
        </div>
      </section>
    </div>
  );
}

function resolveLocale(lang: string): Locale {
  if (!isSupportedLocale(lang)) {
    return i18n.defaultLocale as Locale;
  }

  return lang as Locale;
}
