"use client";

import { useMemo, useState } from "react";
import type { ComponentType } from "react";

import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import {
  BarChart3,
  CalendarRange,
  RefreshCcw,
  ShieldCheck,
  ShoppingCart,
  Users
} from "lucide-react";

type IconType = ComponentType<{ className?: string }>;

type MetricCard = {
  label: string;
  value: string;
  detail: string;
  icon: IconType;
};

type TimelineStep = {
  title: string;
  detail: string;
  icon: IconType;
};

type RepurchaseCycleSimulatorProps = {
  className?: string;
};

const CUSTOMER_COHORTS = [240, 540, 960] as const; // active members monitored for repurchase
const REPURCHASE_RATES = [0.48, 0.62, 0.78] as const; // percentage of cohort expected to reorder each cycle
const ORDER_VALUES = [68, 96, 138] as const; // average USD order value per repurchase

export default function RepurchaseCycleSimulator({
  className
}: RepurchaseCycleSimulatorProps) {
  const [cohort, setCohort] = useState<typeof CUSTOMER_COHORTS[number]>(CUSTOMER_COHORTS[1]);
  const [repurchaseRate, setRepurchaseRate] = useState<typeof REPURCHASE_RATES[number]>(REPURCHASE_RATES[1]);
  const [orderValue, setOrderValue] = useState<typeof ORDER_VALUES[number]>(ORDER_VALUES[1]);

  const currencyFormatter = useMemo(
    () =>
      new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: "USD",
        maximumFractionDigits: 0
      }),
    []
  );

  const numberFormatter = useMemo(
    () =>
      new Intl.NumberFormat("en-US", {
        maximumFractionDigits: 0
      }),
    []
  );

  const percentageFormatter = useMemo(
    () =>
      new Intl.NumberFormat("en-US", {
        style: "percent",
        minimumFractionDigits: 0,
        maximumFractionDigits: 0
      }),
    []
  );

  const stats = useMemo(() => {
    const activeReorders = Math.round(cohort * repurchaseRate);
    const monthlyVolume = activeReorders * orderValue;
    const payoutPool = monthlyVolume * 0.32; // 32% allocated to commissions and leadership pools
    const loyaltyCredits = monthlyVolume * 0.12; // credits applied to encourage the next order
    const complianceHold = monthlyVolume * 0.07; // reserve to clear tax, KYC, and clawbacks
    const retentionRate = repurchaseRate * 0.92 + 0.06; // model loyalty uplift from Cloud MLM nudges
    const cycleDays = 30;

    const metrics: MetricCard[] = [
      {
        label: "Active repurchase orders",
        value: numberFormatter.format(activeReorders),
        detail: "Members expected to meet the rolling reorder window this month.",
        icon: Users
      },
      {
        label: "Projected volume",
        value: currencyFormatter.format(monthlyVolume),
        detail: "Gross merchandise value generated by recurring purchases.",
        icon: ShoppingCart
      },
      {
        label: "Commission pool",
        value: currencyFormatter.format(payoutPool),
        detail: "Allocated for differential bonuses, incentives, and team overrides.",
        icon: BarChart3
      },
      {
        label: "Compliance reserve",
        value: currencyFormatter.format(complianceHold),
        detail: "Held until KYC, tax, and product delivery confirmations clear.",
        icon: ShieldCheck
      }
    ];

    const timeline: TimelineStep[] = [
      {
        title: "Week 1 – Forecast inventory",
        detail: `Reserve ${currencyFormatter.format(monthlyVolume * 0.25)} in stock to cover ${numberFormatter.format(activeReorders)} reorders and regional safety stock requirements.`,
        icon: ShoppingCart
      },
      {
        title: "Week 2 – Loyalty campaign",
        detail: `Drop ${currencyFormatter.format(loyaltyCredits)} in loyalty credits and trigger AI nudges for members lagging behind the ${percentageFormatter.format(repurchaseRate)} repurchase goal.`,
        icon: RefreshCcw
      },
      {
        title: "Week 3 – Compliance sweep",
        detail: `Finance and compliance review ${currencyFormatter.format(complianceHold)} flagged payouts before disbursement, with audit notes stored in Cloud MLM Software.`,
        icon: ShieldCheck
      },
      {
        title: "Week 4 – Commission closeout",
        detail: `Release ${currencyFormatter.format(payoutPool - complianceHold)} in net commissions and publish retention dashboards targeting ${percentageFormatter.format(retentionRate)} loyalty.`,
        icon: BarChart3
      }
    ];

    return {
      activeReorders,
      monthlyVolume,
      payoutPool,
      loyaltyCredits,
      complianceHold,
      retentionRate,
      cycleDays,
      metrics,
      timeline
    };
  }, [cohort, repurchaseRate, orderValue, currencyFormatter, numberFormatter, percentageFormatter]);

  return (
    <div
      className={cn(
        "grid h-full w-full gap-6 rounded-3xl border border-border/60 bg-background/80 p-6 shadow-lg backdrop-blur dark:border-white/10",
        className
      )}
    >
      <header className="space-y-2">
        <p className="text-sm font-semibold uppercase tracking-wide text-primary dark:text-primary/80">Repurchase cycle planner</p>
        <h3 className="text-xl font-semibold text-foreground dark:text-white">
          Model recurring orders, compliance holds, and payout pacing in one glance.
        </h3>
        <p className="text-sm text-muted-foreground dark:text-white/70">
          Adjust cohort size, repurchase health, and product value to stress-test how Cloud MLM Software orchestrates each thirty-day cycle.
        </p>
      </header>

      <div className="grid gap-5">
        <div className="grid gap-2">
          <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Cohort monitored</span>
          <div className="flex flex-wrap gap-2">
            {CUSTOMER_COHORTS.map((option) => (
              <Button
                key={option}
                type="button"
                size="sm"
                variant={option === cohort ? "default" : "outline"}
                onClick={() => setCohort(option)}
              >
                {numberFormatter.format(option)} members
              </Button>
            ))}
          </div>
        </div>

        <div className="grid gap-2">
          <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Repurchase rate</span>
          <div className="flex flex-wrap gap-2">
            {REPURCHASE_RATES.map((option) => (
              <Button
                key={option}
                type="button"
                size="sm"
                variant={option === repurchaseRate ? "default" : "outline"}
                onClick={() => setRepurchaseRate(option)}
              >
                {percentageFormatter.format(option)}
              </Button>
            ))}
          </div>
        </div>

        <div className="grid gap-2">
          <span className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Average order value</span>
          <div className="flex flex-wrap gap-2">
            {ORDER_VALUES.map((option) => (
              <Button
                key={option}
                type="button"
                size="sm"
                variant={option === orderValue ? "default" : "outline"}
                onClick={() => setOrderValue(option)}
              >
                {currencyFormatter.format(option)}
              </Button>
            ))}
          </div>
        </div>
      </div>

      <div className="grid gap-5">
        <div className="grid gap-3 sm:grid-cols-2">
          {stats.metrics.map((metric) => (
            <article
              key={metric.label}
              className="flex gap-3 rounded-2xl border border-border/50 bg-muted/40 p-4 dark:border-white/10 dark:bg-white/5"
            >
              <metric.icon className="mt-1 h-5 w-5 text-primary" aria-hidden />
              <div className="space-y-1">
                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                  {metric.label}
                </p>
                <p className="text-lg font-semibold text-foreground dark:text-white">{metric.value}</p>
                <p className="text-xs text-muted-foreground dark:text-white/70">{metric.detail}</p>
              </div>
            </article>
          ))}
        </div>

        <div className="space-y-3">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            <CalendarRange className="h-4 w-4" aria-hidden />
            {stats.cycleDays}-day cadence
          </div>
          <div className="grid gap-3">
            {stats.timeline.map((step) => (
              <article
                key={step.title}
                className="rounded-2xl border border-border/40 bg-background/70 p-4 dark:border-white/10 dark:bg-white/5"
              >
                <div className="flex items-start gap-3">
                  <step.icon className="mt-1 h-5 w-5 text-primary" aria-hidden />
                  <div className="space-y-1">
                    <p className="text-sm font-semibold text-foreground dark:text-white">{step.title}</p>
                    <p className="text-xs text-muted-foreground dark:text-white/70">{step.detail}</p>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </div>

        <div className="rounded-2xl border border-primary/30 bg-primary/10 p-4 text-xs text-primary dark:border-white/10 dark:bg-white/10 dark:text-white">
          Cloud MLM Software tracks retention, payouts, and compliance notes in real time so founders and finance teams can intervene before repurchase momentum slides.
        </div>
      </div>
    </div>
  );
}
