import type { Metadata } from "next";
import Link from "next/link";

import type { SupportedLocale } from "@/config/site";
import { isSupportedLocale } from "@/lib/i18n-utils";
import { buildLocalizedPath } from "@/lib/locale-links";
import type { Locale } from "@/i18n-config";
import { i18n } from "@/i18n-config";
import { Button } from "@/components/ui/button";
import {
  ArrowRight,
  Globe,
  LayoutGrid,
  ShoppingBag,
  ShoppingCart,
  Store,
  TrendingUp
} from "lucide-react";

export const dynamic = "force-static";

const INTRO_PARAGRAPH =
  "What are the top-notch e-commerce MLM companies of 2025? This case study explores the leading e-commerce MLM companies that are running effectively. Prior to diving into the company information, let’s have a look at the terms e-commerce and MLM separately.";

const MLM_PARAGRAPH =
  "Multi-level marketing is a business model that operates through independent distributors who sell and promote their products and services to potential customers. Along with the promotion of their services, they focus on recruiting new members to the network and earning a passive income from their sales.";

const ECOM_PARAGRAPH =
  "E-commerce is the practice of selling and buying products online. This is done through any device such as computers, smartphones, tablets, etc. They use social media platforms and websites to initiate sales over the Internet.";

const HYBRID_PARAGRAPH =
  "As we know, MLM and e-commerce are two distinct business structures with key differences. The concept behind e-commerce MLM is profoundly captivating. E-commerce multi-level marketing combines the principles of network marketing and e-commerce. In simple terms, it involves the promotion of products and services via online platforms by building a network of independent distributors who become their salesforce. The commission structure of e-commerce MLM companies includes earnings from their individual sales and the sales generated by their downlines as well.";

type Company = {
  name: string;
  description: string;
};

const COMPANIES: Company[] = [
  {
    name: "Amway",
    description:
      "Amway blends a global direct selling network with personalized e-commerce sites for distributors. Customers can browse curated storefronts, receive recommendations, and complete purchases online while distributors track engagement."
  },
  {
    name: "Forever Living Products",
    description:
      "Forever Living specializes in aloe-based health and wellness goods. Its distributors combine traditional relationship selling with digital storefronts to reach customers worldwide and sustain recurring orders."
  },
  {
    name: "Herbalife",
    description:
      "Herbalife’s nutrition-focused catalog thrives on a hybrid model. Distributors leverage virtual catalogues, subscription programs, and healthy lifestyle content to convert global audiences."
  },
  {
    name: "Avon",
    description:
      "Avon continues to dominate beauty and personal care through a vast consultant community. E-commerce tools empower representatives to demo products online, manage replenishment, and launch limited campaigns."
  },
  {
    name: "Vestige",
    description:
      "Vestige, based in India, scales wellness, personal care, and home essentials via multilingual portals, automated commission engines, and onboarding flows tailored for fast-growing teams."
  },
  {
    name: "Oriflame",
    description:
      "Oriflame’s Swedish roots power a beauty portfolio sold across 60+ countries. Consultants run branded microsites, host virtual events, and tap localized logistics to deliver skincare and fragrance lines."
  },
  {
    name: "RCM",
    description:
      "Right Concept Marketing (RCM) supports distributors with dashboards for tracking sales, payouts, and genealogy. Its broad catalog—from agriculture to home care—ships directly through integrated carts."
  },
  {
    name: "Modicare",
    description:
      "Modicare fields a diversified range of nutrition and personal products. Entrepreneurs manage customer journeys digitally, tapping loyalty rewards, subscription ordering, and localized offers."
  },
  {
    name: "Mary Kay",
    description:
      "Mary Kay consultants deliver cosmetics through virtual try-ons, curated skincare regimens, and social commerce. Its e-commerce engine backs inventory management, clienteling, and order fulfilment."
  },
  {
    name: "Tupperware",
    description:
      "Tupperware’s household innovations meet digital convenience. Consultants host interactive demos, automate reorders, and merchandise kitchen solutions via modern e-commerce experiences."
  }
];

const ADVANTAGES = [
  {
    title: "Increased reach",
    description:
      "MLM organizations can transcend geography by pairing online storefronts with social discovery. Global reach expands lead pools and unlocks niche customer segments."
  },
  {
    title: "Convenience and accessibility",
    description:
      "Distributors run their business anywhere with responsive portals, while customers enjoy on-demand ordering, subscription deliveries, and localized payment options."
  },
  {
    title: "Flexibility and adaptability",
    description:
      "E-commerce lets teams respond quickly to market trends—launching new bundles, testing pricing, and personalizing promotions without waiting for traditional retail cycles."
  }
];

const CONCLUSION_PARAGRAPH =
  "It’s important to consider that the benefits might change depending on how e-commerce is implemented and carried out specifically within the MLM business model. E-commerce MLM companies and distributors must carefully incorporate practices that support their overarching business strategy and objectives.";

const AUTHOR = {
  name: "Experienced Research Analyst",
  bio: "Experienced Research Analyst with in-depth knowledge of the MLM industry, including emerging trends and innovative strategies. Passionate about utilizing technology to drive growth and optimize business processes. Adept at analyzing market dynamics, delivering actionable insights, and staying ahead of industry developments."
};

export async function generateMetadata({
  params
}: {
  params: { lang: SupportedLocale };
}): Promise<Metadata> {
  const locale = resolveLocale(params.lang);
  const title = "Top 10 E-commerce MLM Companies in 2025";
  const description =
    "Explore how leaders like Amway, Forever Living, Herbalife, and more combine e-commerce and network marketing to scale revenue and reach.";

  return {
    title,
    description,
    alternates: {
      canonical: buildLocalizedPath("/blog/top-10-e-commerce-mlm-companies", locale)
    },
    openGraph: {
      title,
      description
    }
  };
}

type EcommerceCompaniesPageProps = {
  params: { lang: SupportedLocale };
};

export default function TopEcommerceMlmCompaniesPage({ params }: EcommerceCompaniesPageProps) {
  const locale = resolveLocale(params.lang);
  const contactHref = buildLocalizedPath("/contact", locale);
  const demoHref = buildLocalizedPath("/free-mlm-software-demo", locale);

  return (
    <div className="space-y-24 pb-24">
      <section className="relative overflow-hidden rounded-3xl border border-indigo-200 bg-gradient-to-br from-indigo-100 via-white to-sky-100 shadow-2xl dark:border-indigo-500/30 dark:from-slate-950 dark:via-slate-900 dark:to-sky-950/40">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(79,70,229,0.24),transparent_60%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,0.24),transparent_60%)] dark:bg-[radial-gradient(circle_at_top_left,rgba(79,70,229,0.12),transparent_65%),radial-gradient(circle_at_bottom_right,rgba(14,165,233,0.14),transparent_72%)]" />
        <div className="relative grid gap-12 px-6 py-20 sm:px-12 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,0.95fr)] xl:px-20">
          <div className="space-y-6">
            <span className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-white/80 px-4 py-1 text-xs font-semibold uppercase tracking-wide text-indigo-700 dark:border-indigo-500/30 dark:bg-slate-900/70 dark:text-indigo-200">
              <ShoppingCart className="h-4 w-4" aria-hidden />
              E-commerce leaders
            </span>
            <h1 className="text-4xl font-semibold leading-tight text-slate-900 sm:text-5xl dark:text-white">
              Top 10 e-commerce MLM companies propelling 2025 growth
            </h1>
            <p className="text-sm leading-6 text-slate-700 dark:text-slate-200">{INTRO_PARAGRAPH}</p>
            <div className="flex flex-wrap gap-3">
              <Button
                asChild
                className="rounded-full bg-indigo-600 px-6 py-2 text-white shadow-lg shadow-indigo-500/30 transition hover:bg-indigo-500 dark:bg-indigo-500 dark:hover:bg-indigo-400"
              >
                <Link href={demoHref}>
                  Modernize your e-commerce MLM
                  <ArrowRight className="ml-2 h-4 w-4" aria-hidden />
                </Link>
              </Button>
              <Button
                asChild
                variant="outline"
                className="rounded-full border-indigo-200 bg-white/80 px-6 py-2 text-indigo-700 transition hover:bg-indigo-100 dark:border-indigo-500/40 dark:bg-slate-900/60 dark:text-indigo-200 dark:hover:bg-slate-800"
              >
                <Link href={contactHref}>Consult with our strategists</Link>
              </Button>
            </div>
          </div>
          <div className="space-y-4 rounded-3xl border border-white/70 bg-white/80 p-8 shadow-2xl backdrop-blur dark:border-white/10 dark:bg-slate-900/70">
            <div className="space-y-3 text-sm leading-6 text-slate-600 dark:text-slate-300">
              <p>{MLM_PARAGRAPH}</p>
              <p>{ECOM_PARAGRAPH}</p>
              <p>{HYBRID_PARAGRAPH}</p>
            </div>
          </div>
        </div>
      </section>

      <section className="container space-y-12">
        <div className="rounded-3xl border border-slate-100 bg-white/80 p-8 shadow-xl dark:border-slate-800 dark:bg-slate-900/70">
          <div className="flex items-center gap-3">
            <Store className="h-6 w-6 text-indigo-600 dark:text-indigo-300" aria-hidden />
            <h2 className="text-3xl font-semibold text-slate-900 dark:text-white">Top 10 e-commerce MLM companies</h2>
          </div>
          <p className="mt-4 text-sm leading-6 text-slate-700 dark:text-slate-200">
            Each organization on this list fuses digital commerce with community-driven selling to expand reach and distributor success.
          </p>
        </div>
        <div className="grid gap-6 lg:grid-cols-2">
          {COMPANIES.map((company) => (
            <div
              key={company.name}
              className="rounded-3xl border border-slate-100 bg-white/80 p-6 shadow-lg transition hover:-translate-y-1 hover:shadow-xl dark:border-slate-800 dark:bg-slate-900/70"
            >
              <h3 className="text-lg font-semibold text-slate-900 dark:text-white">{company.name}</h3>
              <p className="mt-3 text-sm leading-6 text-slate-700 dark:text-slate-200">{company.description}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="container space-y-10">
        <div className="rounded-3xl border border-indigo-200 bg-indigo-50/70 p-8 shadow-xl dark:border-indigo-500/40 dark:bg-indigo-500/10">
          <div className="flex items-center gap-3">
            <TrendingUp className="h-6 w-6 text-indigo-600 dark:text-indigo-300" aria-hidden />
            <h2 className="text-2xl font-semibold text-slate-900 dark:text-white">Here are some advantages to MLM e-commerce</h2>
          </div>
          <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {ADVANTAGES.map((advantage) => (
              <div key={advantage.title} className="rounded-2xl border border-white/70 bg-white/80 p-5 dark:border-white/10 dark:bg-slate-900/70">
                <h3 className="text-sm font-semibold uppercase tracking-wide text-indigo-700 dark:text-indigo-200">{advantage.title}</h3>
                <p className="mt-2 text-sm leading-6 text-slate-700 dark:text-slate-200">{advantage.description}</p>
              </div>
            ))}
          </div>
        </div>
        <div className="rounded-3xl border border-slate-100 bg-white/80 p-8 shadow-xl dark:border-slate-800 dark:bg-slate-900/70">
          <p className="text-sm leading-6 text-slate-700 dark:text-slate-200">{CONCLUSION_PARAGRAPH}</p>
        </div>
        <div className="rounded-3xl border border-slate-200 bg-slate-50/70 p-8 shadow-xl dark:border-slate-700 dark:bg-slate-900/70">
          <p className="text-sm font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">About The Author</p>
          <p className="mt-3 text-2xl font-semibold text-slate-900 dark:text-white">{AUTHOR.name}</p>
          <p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{AUTHOR.bio}</p>
        </div>
      </section>
    </div>
  );
}

function resolveLocale(lang: string): Locale {
  return (isSupportedLocale(lang) ? lang : i18n.defaultLocale) as Locale;
}

